[functions.tally-webhook]
verify_jwt = false

[functions.group-invite]
verify_jwt = true

[functions.join-group]
verify_jwt = true

[functions.create-checkout-session]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.send-email]
verify_jwt = true

[functions.charge-scheduled-payments]
verify_jwt = false
