-- Phase 7: secure administrator content management for group trips,
-- resources, and blog posts.

-- Capability used by the browser admin portal. Administrator membership is
-- still anchored to auth.users through admin_users.id.
alter table public.admin_users
  add column if not exists can_edit_resources boolean not null default true;

-- Content fields needed by the public pages and editor.
alter table public.trips
  add column if not exists hero_kicker text,
  add column if not exists booking_deadline date,
  add column if not exists is_featured boolean not null default false,
  add column if not exists sort_order integer not null default 0;

update public.trips set status = 'completed'
where dates_end < current_date and status = 'active';

alter table public.trips alter column status set not null;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'trips_status_check'
      and conrelid = 'public.trips'::regclass
  ) then
    alter table public.trips
      add constraint trips_status_check
      check (status in ('draft', 'active', 'completed', 'archived', 'cancelled'));
  end if;
end $$;

alter table public.resources
  add column if not exists updated_at timestamptz not null default now(),
  add column if not exists created_by uuid references auth.users(id) on delete set null,
  add column if not exists updated_by uuid references auth.users(id) on delete set null;

alter table public.blog_posts
  add column if not exists link_url text,
  add column if not exists published_at timestamptz,
  add column if not exists created_by uuid references auth.users(id) on delete set null,
  add column if not exists updated_by uuid references auth.users(id) on delete set null;

-- The existing empty blog table had a required bigint ID without a default.
-- Give it an identity so browser inserts remain safe under concurrent use.
do $$
begin
  if pg_get_serial_sequence('public.blog_posts', 'id') is null then
    alter table public.blog_posts
      alter column id add generated by default as identity;
  end if;
end $$;

-- Remove repeated seed rows while keeping the oldest canonical resource.
delete from public.resources
where resource_id in (
  select resource_id
  from (
    select resource_id,
           row_number() over (
             partition by lower(trim(title)), lower(trim(coalesce(category, '')))
             order by created_at nulls last, resource_id
           ) as duplicate_number
    from public.resources
  ) ranked
  where duplicate_number > 1
);

create unique index if not exists resources_title_category_unique
  on public.resources (lower(trim(title)), lower(trim(coalesce(category, ''))));

-- Reconcile the resources currently displayed by the public site into the
-- editable source of truth.
insert into public.resources
  (title, description, category, icon, link_url, link_label, sort_order, is_active)
values
  ('Hotels.com', 'Compare thousands of hotels with flexible cancellation and rewards on eligible stays.', 'hotel', '🏨', 'https://www.hotels.com', 'Search Hotels →', 1, true),
  ('Expedia Hotels', 'Bundle flights and hotels and compare resort properties and city stays.', 'hotel', '🌍', 'https://www.expedia.com/Hotels', 'Browse on Expedia →', 2, true),
  ('VRBO — Vacation Rentals', 'Vacation homes can give larger groups more shared space and flexibility.', 'hotel', '🏡', 'https://www.vrbo.com', 'Find a Rental →', 3, true),
  ('Unique Stays', 'Browse boutique properties, villas, and other distinctive accommodations.', 'hotel', '🛖', 'https://www.airbnb.com', 'Browse Unique Stays →', 4, true),
  ('Custom & Private Trips', 'Tailored experiences designed around your dreams, budget, and timeline.', 'service', '🎯', '/custom-trip-form', 'Start Planning →', 1, true),
  ('Corporate Travel', 'Team retreats, conferences, and events with coordinated travel logistics.', 'service', '💼', '/forms-corporate-travel.html', 'Plan Your Retreat →', 2, true),
  ('Destination Weddings', 'Destination celebrations planned around your guests and chosen location.', 'service', '💍', '/forms-destination-weddings.html', 'Start Planning →', 3, true),
  ('On-Tour Travel Management', 'Travel coordination for touring artists, entertainers, and their teams.', 'service', '🎤', '/on-tour-travel-management-form.html', 'Get Tour Support →', 4, true),
  ('Travel Consulting', 'Professional guidance for travelers who need planning support or a second opinion.', 'service', '🧭', '/forms-travel-consulting.html', 'Get Expert Help →', 5, true),
  ('Packing Guides', 'Smart packing strategies for concerts, festivals, resorts, and international travel.', 'guide', '🧳', '/blog', 'Read Packing Tips →', 1, true),
  ('Travel Documents', 'Checklists for passports, identification, insurance, and confirmations.', 'guide', '📋', '/blog', 'View Checklist →', 2, true)
on conflict (lower(trim(title)), lower(trim(coalesce(category, '')))) do update
set description = excluded.description,
    icon = excluded.icon,
    link_url = excluded.link_url,
    link_label = excluded.link_label,
    sort_order = excluded.sort_order,
    updated_at = now();

-- Move the existing visible Blog cards into editable records.
insert into public.blog_posts
  (title, slug, category, content, featured_image_url, excerpt, is_published, link_url, published_at)
values
  ('Your Complete Guide to Essence Festival of Culture 2026', 'complete-guide-essence-festival-2026', 'Destination Guide', 'Everything you need to know before attending the world''s largest Black cultural celebration — what to wear, where to eat, how to get around, and how to prepare for a group trip to New Orleans.', null, 'Everything you need to know before attending the world''s largest Black cultural celebration.', true, '/essence-festival-new-orleans-july-3-5-2026', now()),
  ('Mary J. Blige Las Vegas Residency — What to Expect', 'mary-j-blige-las-vegas-residency-guide', 'Destination Guide', 'Prepare for Mary J. Blige at Dolby Live with practical information about the venue, Las Vegas transportation, group travel, and the October 2026 experience.', null, 'The Queen of Hip-Hop Soul at Dolby Live, plus the details travelers need before the show.', true, '/mary-j-blige-my-life-my-story-las-vegas-oct-22-24-2026', now()),
  ('Atlanta R&B Lovers Tour — Keith Sweat, Dru Hill & More', 'atlanta-rnb-lovers-tour-guide', 'Destination Guide', 'Plan an Atlanta R&B weekend around State Farm Arena, including transportation, dining, and group-travel preparation.', null, 'A practical guide to the concert weekend and experiencing Atlanta with your group.', true, '/keith-sweat-r-and-b-tour-atlanta-august-29-2026', now()),
  ('Napa Juneteenth — Wine, Culture & Community', 'napa-juneteenth-wine-culture-community', 'Destination Guide', 'Explore wine country with an emphasis on culture, community, responsible transportation, and thoughtful group planning.', null, 'Wine country, culture, and community in one memorable group-travel experience.', true, '/napa-juneteenth-june-18-21-2026', now()),
  ('The Ultimate Group Trip Packing List', 'ultimate-group-trip-packing-list', 'Packing Guide', 'Start with identification, payment methods, prescriptions, chargers, and confirmed travel documents. Add destination-specific clothing, comfortable shoes, weather protection, and one compact day bag. Coordinate shared items with the group so everyone does not pack the same supplies.', null, 'What to bring, what to share, and what to leave behind on a group trip.', true, null, now()),
  ('The Complete Travel Documents Checklist', 'complete-travel-documents-checklist', 'Travel Documents', 'Confirm identification requirements, passport validity, visas when applicable, travel insurance, booking confirmations, emergency contacts, medical information, and copies stored securely away from the originals.', null, 'The essential documents to verify before departure.', true, null, now()),
  ('First Group Trip? Here’s What You Need to Know', 'first-group-trip-what-to-know', 'First-Time Traveler', 'Review the itinerary, payment deadlines, group expectations, room arrangements, and contact information before departure. Ask questions early and keep key confirmations available while traveling.', null, 'A clear introduction to booking, preparing for, and enjoying a group trip.', true, '/how-it-works', now())
on conflict (slug) do update
set title = excluded.title,
    category = excluded.category,
    content = excluded.content,
    excerpt = excluded.excerpt,
    link_url = excluded.link_url,
    updated_at = now();

create index if not exists trips_public_listing_idx
  on public.trips (sort_order, dates_start, trip_id)
  where status = 'active';
create index if not exists resources_public_listing_idx
  on public.resources (category, sort_order, resource_id)
  where is_active;
create index if not exists blog_posts_public_listing_idx
  on public.blog_posts (published_at desc, id desc)
  where is_published;
create index if not exists resources_created_by_idx on public.resources(created_by)
  where created_by is not null;
create index if not exists resources_updated_by_idx on public.resources(updated_by)
  where updated_by is not null;
create index if not exists blog_posts_created_by_idx on public.blog_posts(created_by)
  where created_by is not null;
create index if not exists blog_posts_updated_by_idx on public.blog_posts(updated_by)
  where updated_by is not null;

drop trigger if exists resources_set_updated_at on public.resources;
create trigger resources_set_updated_at
before update on public.resources
for each row execute function private.set_trv_updated_at();

drop trigger if exists blog_posts_set_updated_at on public.blog_posts;
create trigger blog_posts_set_updated_at
before update on public.blog_posts
for each row execute function private.set_trv_updated_at();

-- Remove permissive/duplicated policies and replace them with explicit roles.
drop policy if exists "Admins can update admin users" on public.admin_users;
drop policy if exists "Admins can update their row" on public.admin_users;
drop policy if exists "Admins can view admin users" on public.admin_users;
drop policy if exists "admin_users: read own row" on public.admin_users;
drop policy if exists "admin_users: update own row" on public.admin_users;
drop policy if exists "admin_users: user can read own row" on public.admin_users;
drop policy if exists "admin_users: user can update own row" on public.admin_users;

create policy "admin_users_read_own_membership"
on public.admin_users for select
to authenticated
using ((select auth.uid()) = id);

drop policy if exists "Admin full access trips" on public.trips;
drop policy if exists "Admins can manage trips" on public.trips;
drop policy if exists "Admins can manage trips table" on public.trips;
drop policy if exists "Anyone can read trips" on public.trips;

create policy "public_reads_active_trips"
on public.trips for select
to anon, authenticated
using (status = 'active');

create policy "trip_admins_read_all"
on public.trips for select
to authenticated
using (
  exists (
    select 1 from public.admin_users au
    where au.id = (select auth.uid()) and au.can_edit_trips
  )
);

create policy "travelers_read_booked_trips"
on public.trips for select
to authenticated
using (
  exists (
    select 1 from public.bookings b
    where b.trip_id = trips.trip_id
      and b.user_id = (select auth.uid())
  )
);

create policy "trip_admins_insert"
on public.trips for insert
to authenticated
with check (
  exists (
    select 1 from public.admin_users au
    where au.id = (select auth.uid()) and au.can_edit_trips
  )
);
create policy "trip_admins_update"
on public.trips for update
to authenticated
using (
  exists (
    select 1 from public.admin_users au
    where au.id = (select auth.uid()) and au.can_edit_trips
  )
)
with check (
  exists (
    select 1 from public.admin_users au
    where au.id = (select auth.uid()) and au.can_edit_trips
  )
);
create policy "trip_admins_delete_unbooked"
on public.trips for delete
to authenticated
using (
  exists (
    select 1 from public.admin_users au
    where au.id = (select auth.uid()) and au.can_edit_trips
  )
  and not exists (
    select 1 from public.bookings b where b.trip_id = trips.trip_id
  )
);

drop policy if exists "admins_manage_trip_packages" on public.trip_packages;
drop policy if exists "anyone_reads_active_trip_packages" on public.trip_packages;

create policy "public_reads_active_trip_packages"
on public.trip_packages for select
to anon, authenticated
using (
  is_active and exists (
    select 1 from public.trips t
    where t.trip_id = trip_packages.trip_id and t.status = 'active'
  )
);
create policy "trip_admins_manage_packages"
on public.trip_packages for all
to authenticated
using (
  exists (
    select 1 from public.admin_users au
    where au.id = (select auth.uid()) and au.can_edit_trips
  )
)
with check (
  exists (
    select 1 from public.admin_users au
    where au.id = (select auth.uid()) and au.can_edit_trips
  )
);

drop policy if exists "Admins can manage resources" on public.resources;
drop policy if exists "Anyone can read resources" on public.resources;

create policy "public_reads_active_resources"
on public.resources for select
to anon, authenticated
using (is_active);
create policy "resource_admins_manage"
on public.resources for all
to authenticated
using (
  exists (
    select 1 from public.admin_users au
    where au.id = (select auth.uid()) and au.can_edit_resources
  )
)
with check (
  exists (
    select 1 from public.admin_users au
    where au.id = (select auth.uid()) and au.can_edit_resources
  )
);

drop policy if exists "Admins can manage blog" on public.blog_posts;
drop policy if exists "Public can view published blog" on public.blog_posts;

create policy "public_reads_published_blog"
on public.blog_posts for select
to anon, authenticated
using (is_published);
create policy "blog_admins_manage"
on public.blog_posts for all
to authenticated
using (
  exists (
    select 1 from public.admin_users au
    where au.id = (select auth.uid()) and au.can_edit_blog
  )
)
with check (
  exists (
    select 1 from public.admin_users au
    where au.id = (select auth.uid()) and au.can_edit_blog
  )
);

revoke insert, update, delete on public.admin_users from anon, authenticated;
grant select on public.admin_users to authenticated;
grant select on public.trips, public.trip_packages, public.resources, public.blog_posts to anon, authenticated;
grant insert, update, delete on public.trips, public.trip_packages, public.resources, public.blog_posts to authenticated;
grant usage, select on sequence public.blog_posts_id_seq to authenticated;

-- Public media is downloadable by URL; only authenticated content admins may
-- upload, replace, list, or delete files through the Storage API.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'content-media',
  'content-media',
  true,
  10485760,
  array['image/jpeg','image/png','image/webp','image/gif']
)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "content_admins_read_media" on storage.objects;
drop policy if exists "content_admins_upload_media" on storage.objects;
drop policy if exists "content_admins_update_media" on storage.objects;
drop policy if exists "content_admins_delete_media" on storage.objects;

create policy "content_admins_read_media"
on storage.objects for select
to authenticated
using (
  bucket_id = 'content-media'
  and exists (
    select 1 from public.admin_users au where au.id = (select auth.uid())
  )
);
create policy "content_admins_upload_media"
on storage.objects for insert
to authenticated
with check (
  bucket_id = 'content-media'
  and exists (
    select 1 from public.admin_users au where au.id = (select auth.uid())
  )
);
create policy "content_admins_update_media"
on storage.objects for update
to authenticated
using (
  bucket_id = 'content-media'
  and exists (
    select 1 from public.admin_users au where au.id = (select auth.uid())
  )
)
with check (
  bucket_id = 'content-media'
  and exists (
    select 1 from public.admin_users au where au.id = (select auth.uid())
  )
);
create policy "content_admins_delete_media"
on storage.objects for delete
to authenticated
using (
  bucket_id = 'content-media'
  and exists (
    select 1 from public.admin_users au where au.id = (select auth.uid())
  )
);
